// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCluvpw2X-KTx3S1lO94SxInjrRmcwsTU8',
    appId: '1:499845253230:web:10804f6a0bbb67a715be7f',
    messagingSenderId: '499845253230',
    projectId: 'cpatrick-7971a',
    authDomain: 'cpatrick-7971a.firebaseapp.com',
    storageBucket: 'cpatrick-7971a.appspot.com',
    measurementId: 'G-C4J3KFPS1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtiUbhyHWuJVfEULDEwU38_nK1q91NgOY',
    appId: '1:499845253230:android:18e70c33768847c215be7f',
    messagingSenderId: '499845253230',
    projectId: 'cpatrick-7971a',
    storageBucket: 'cpatrick-7971a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjaSsiO8r-L4wQ7KaU7gnY6LPkoSlMLGo',
    appId: '1:499845253230:ios:f641f8d4cb73fe5a15be7f',
    messagingSenderId: '499845253230',
    projectId: 'cpatrick-7971a',
    storageBucket: 'cpatrick-7971a.appspot.com',
    iosBundleId: 'com.ashmawi.new3c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjaSsiO8r-L4wQ7KaU7gnY6LPkoSlMLGo',
    appId: '1:499845253230:ios:f641f8d4cb73fe5a15be7f',
    messagingSenderId: '499845253230',
    projectId: 'cpatrick-7971a',
    storageBucket: 'cpatrick-7971a.appspot.com',
    iosBundleId: 'com.ashmawi.new3c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCluvpw2X-KTx3S1lO94SxInjrRmcwsTU8',
    appId: '1:499845253230:web:9edbc330c380c03615be7f',
    messagingSenderId: '499845253230',
    projectId: 'cpatrick-7971a',
    authDomain: 'cpatrick-7971a.firebaseapp.com',
    storageBucket: 'cpatrick-7971a.appspot.com',
    measurementId: 'G-4P8EKC8JGS',
  );
}
